easy_admin:
  entities:
    Picture:
      # ...
      list:
        fields:
            - { property: 'image', type: 'image', base_path: '%app.path.images%'}
        # ...
        show:
          fields:
            - { property: 'image', type: 'image', base_path: '%app.path.images%'}
        # ...
        form:
          fields:
            - { property: 'imageFile', type: 'vich_image' }
