vich_uploader:
    db_driver: orm

    mappings:
        user:
            uri_prefix: /images/userpp
            upload_destination: '%kernel.project_dir%/public/images/userpp'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
